name: MRF NASA Project CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    env:
      CI: true
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --prefix server
      - run: npm install --prefix client
      - run: npm run build --prefix client
      - run: npm test
