name: MRF NASA Project CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js version 16
        uses: actions/setup-node@v4
        with:
          node-version: "16"
      - run: npm install --prefix server
      - run: npm install --prefix client
      - run: npm run build --prefix client
